<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="HandheldFriendly" content="True">
    <meta name="MobileOptimized" content="480">
    <meta name="viewport" content="width=device-width, height=device-height initial-scale=1.0, maximum-scale=1.0, user-scalable=0">

    <title>Basic try-catch-finally Exception Handling in Java</title>

    <meta name="description" content="This tutorial explains how the basic try-catch-finally exception handling mechanisms work in Java.">
    <meta name="keywords"    content="java exception handling try catch finally">
    <meta name="author" content="Jakob Jenkov">

    <meta name="twitter:card" content="summary_large_image" >
    <meta name="twitter:site" content="@jjenkov">
    <meta name="twitter:title" content="Basic try-catch-finally Exception Handling in Java">
    <meta name="twitter:description" content="This tutorial explains how the basic try-catch-finally exception handling mechanisms work in Java.">
    <meta name="twitter:creator" content="@jjenkov">
    <meta name="twitter:domain" content="jenkov.com">

    <meta name="twitter:image:src" content="http://tutorials.jenkov.com/images/java-exception-handling/java-exception-handling-teaser-500-300.png">

    <meta name="og:type"  content="article"/>
    <meta name="og:title" content="Basic try-catch-finally Exception Handling in Java"/>
    <meta property="og:url"   content="http://tutorials.jenkov.com/java-exception-handling/basic-try-catch-finally.html"/>
    <meta property="og:description" content="This tutorial explains how the basic try-catch-finally exception handling mechanisms work in Java."/>

    <meta property="og:image" content="http://tutorials.jenkov.com/images/java-exception-handling/java-exception-handling-teaser-500-300.png"/>

    <link href="https://plus.google.com/108227213807945109821" rel="publisher" />

    <meta name="google-site-verification" content="i_TwzdElg-by5uXLvyAjuIaCjxo0yjtW8LdRPUDEEcw" />

    <!-- jQuery -->
    <!--<script src="https://code.jquery.com/jquery-1.12.0.min.js"></script> -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>

</head>
<body>
<style>
body {background-color: #f0f0f0;background-image: linear-gradient(180deg, #f0f0f0, #e0e0e0);}
.dataTable th, .dataTable td { padding: 2px 8px; }
</style>
<style id="layoutCss"></style>
<style id="jqcCss"></style>
<style id="articleCss"></style>
<style id="navBarCss"></style>
<style>
code  { font-size: 14px; }
</style>

<script>
lcv = "4";
ls = localStorage;
cacheLoaded = false;
pageLoaded = false;

var prevArticleInCategory = "/java-exception-handling/index.html";
var nextArticleInCategory = "/java-exception-handling/try-with-resources.html";
</script>

<script id="jqcJs" ></script>
<script id="bottomNavBarModule" ></script>


<script>
function jsonp(url) {
    var script   = document.createElement("script"); script.type = "text/javascript"; script.src = url;
    document.body.appendChild(script);
}
function insertById(ids) {
    for(var i=0, n=ids.length; i < n; i++) {
        var el = document.getElementById(ids[i]);
        if(el != null) { el.innerHTML = localStorage[ids[i]]; }
    }
}
function insertByClass(ids) {
    for(var i=0, n=ids.length; i<n; i++) {
        var els = document.getElementsByClassName(ids[i]);
        for(var j=0,m=els.length; j<m; j++) { els[j].innerHTML = localStorage[ids[i]]; }
    }
}
function init() {
    if(cacheLoaded == true && pageLoaded == true) {
        console.log("initializing page");
        insertById(["layoutCss", "jqcCss", "topBarLogo", "articleCss", "navBarCss", "bottomNavBar", "bottomNavBarModule", "jqcJs"]);
        insertByClass(["authorPhoto", "authorSocialLinks", "newsletterForm", "googlePlusShare"]);
        $(document).ready(function() { bottomNavBarModule(); });
        console.log("page initialized");
    }
}
if(ls.lcv != lcv) {
    for(var i=0; i < ls.length; i++){
        ls.removeItem(ls.key(i));
    }
    jsonp("/cached-" + lcv + ".js");
    console.log("cache cleared");
} else {
    cacheLoaded = true;
}
ls.lcv = lcv;
</script>
<!-- jqComponents -->


<script>
articleLen = 13425;
adRandom = Math.random() * 100;

function dw(text) { document.write(text); }

function writeAd(adSlot, w, h) {
 dw("<script async src='//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js'><"); dw("/script>");
 dw("<ins class='adsbygoogle' style='display:inline-block;width:" + w + "px;height:" + h + "px' data-ad-client='ca-pub-5569543489255665' data-ad-slot='" +  adSlot + "'></ins>");
 dw("<script>");
 dw("(adsbygoogle = window.adsbygoogle || []).push({});");
 dw("<"); dw("/script>");
}

function topAdStyles(w, mT, mB) {
    var adEl = document.getElementById("topAds");
    adEl.style.width = (w + "px"); adEl.style.marginTop = (mT + "px"); adEl.style.marginBottom = (mB + "px"); adEl.style.marginRight = "auto"; adEl.style.marginLeft = "auto";
}

function bottomAdStyles(elId, w, mT, mB) {
    var adEl = document.getElementById(elId);
    adEl.style.width = (w + "px"); adEl.style.marginTop = (mT + "px"); adEl.style.marginBottom = (mB + "px"); adEl.style.marginRight = "auto"; adEl.style.marginLeft = "auto";
}
</script>


<div id="topBar">
<div jqc-row jqc-row-paddings="0:0 3:24">
    <div jqc-cell="0:12c">
        <div id="topBarContent">
        <div id="topBarLogo"></div>
        <div id="topBarPhrase">Tech and Media Labs</div>
        <div id="topBarMenu">
        <a href="../index.html">Tutorials</a>
        <a href="http://jenkov.com/about/index.html">About</a>
        <a href="http://jenkov.com/rss.xml">RSS</a>
        </div>
        </div>
    </div>
</div>
</div>

<div id="cookieNote">
<div jqc-row jqc-row-widths="0:100% 4:1200" jqc-row-paddings="0:0 3:24">
    <div jqc-cell="0:12c" >
        <div class="card">
            This site uses cookies to improve the user experience. <button onclick="hideCookieNote()">OK</button>
        </div>
    </div>
</div>
</div>

<script>
function hideCookieNote() { document.getElementById("cookieNote").innerHTML = ""; ls.cookieNote = 0; }

if(ls.cookieNote == 0) {
    hideCookieNote();
}
</script>

<div jqc-row jqc-row-widths="0:100% 4:1200" jqc-row-paddings="0:0">
    <div jqc-cell="0:12c">
        <div id="topAds">
            <script>
                var adEl = document.getElementById("topAds");
                if(window.innerWidth > 970) {
                    if(adRandom <= 5){
                        writeAd("6094206201", 970, 90); /* wider ad - 5% of page views */
                        topAdStyles(970, 20, 20);
                    } else {
                        writeAd("7630855405", 728, 90); /* standard ad */
                        topAdStyles(728, 20, 20);
                    }
                } else if(window.innerWidth >= 728 && window.innerWidth <= 970)  {  /* Tutorials - Top Banner */
                    writeAd("7630855405", 728, 90);
                    topAdStyles(728, 20, 20);
                } else {  /* Tutorials - Top Banner - Mobile */
                    writeAd("3297914607", 320, 50);
                    topAdStyles(320, 10, 0);
                }
            </script>
        </div>
    </div>
</div>

<div id="main">

    <div jqc-row jqc-row-widths="0:100% 4:1200" jqc-column-counts="0:24" jqc-row-paddings="0:0 3:24" jqc-cell-spacings="0:8">
        <div jqc-cell="0:0c  3:7c" >
            <div id="trailToc" class="card">
                <div id='trailTitle'>Java Exception Handling</div><ol><li><a href="index.html">Java Exception Handling</a></li><li><a href="basic-try-catch-finally.html"><b>Basic try-catch-finally Exception Handling in Java</b></a></li><li><a href="try-with-resources.html">Try-with-resources in Java 7</a></li><li><a href="catching-multiple-exceptions.html">Catching Multiple Exceptions in Java 7</a></li><li><a href="exception-hierarchies.html">Exception Hierarchies</a></li><li><a href="checked-or-unchecked-exceptions.html">Checked or Unchecked Exceptions?</a></li><li><a href="exception-wrapping.html">Exception Wrapping</a></li><li><a href="fail-safe-exception-handling.html">Fail Safe Exception Handling</a></li><li><a href="pluggable-exception-handlers.html">Pluggable Exception Handlers</a></li><li><a href="logging-where-to-log-exceptions.html">Logging Exceptions: Where to Log Exceptions?</a></li><li><a href="validation-throw-exceptions-early.html">Validation - Throw Exceptions Early</a></li><li><a href="validation-throw-exception-or-return-false.html">Validation - Throw Exception or Return False?</a></li><li><a href="exception-handling-templates.html">Exception Handling Templates in Java</a></li><li><a href="exception-enrichment.html">Exception Enrichment in Java</a></li><li><a href="../exception-handling-strategies/execution-context.html">Execution Context</a></li></ol>
            </div>

            <br><br>
            <!-- Left Bar Adsense Banner Ad -->
            <div id="side-ads">
                <script>
                if(window.innerWidth >= 900){
                    if(adRandom <= 94)     { writeAd("5873880207", 300,  600);}
                    else if(adRandom < 96) { writeAd("3389666608", 160,  600);}
                    else                   { writeAd("4257546205", 300, 1050);}
                }
            </script>
            </div>

            <br><br>


            <div style="display: none;" class="card newsletterForm">
            </div>

        </div>
        <div jqc-cell="0:24c 3:17c" >


            <div class="card">
            <h1>Basic try-catch-finally Exception Handling in Java</h1>

            <div id="mainBody">

                <div id="pageToc" itemscope itemtype="http://schema.org/SiteNavigationElement">
                    <ul><li><a href="#the-call-stack-explained">The Call Stack Explained</a></li><li><a href="#throwing-exceptions">Throwing Exceptions</a></li><li><a href="#catching-exceptions">Catching Exceptions</a></li><li><a href="#propagating-exceptions">Propagating Exceptions</a></li><li><a href="#example-catching-ioexception">Example: Catching IOException's</a></li><li><a href="#example-propagating-ioexception">Example: Propagating IOException's</a></li><li><a href="#finally">Finally</a></li><li><a href="#catch-or-propagating-exceptions">Catch or Propagate Exceptions?</a></li></ul>
                </div>
                <div id="lastUpdate">
                    <table><tr><td class="authorPhoto"></td>
                            <td><p style="margin: 0px 0px 6px 0px;">
                                    Jakob Jenkov<br>
                                    Last update: 2014-06-23
                                </p>
                                <div class="authorSocialLinks"></div>
                            </td>
                        </tr>
                    </table>
                </div>

                <p>
    This text summarizes the basics of how try-catch-finally clause error handling works.
    The examples are in Java, but the rules are the same for C#. The only difference between
    Java and C# exceptions is that C# doesn't have checked exceptions. Checked and unchecked
    exceptions are explained in more detail in a different text.
</p>

<p>
    Exceptions are used in a program to signal that some error or exceptional situation has
    occurred, and that it doesn't make sense to continue the program flow until
    the exception has been handled. A method may throw an exception for many reasons,
    for instance if the input parameters are invalid (negative when expecting positive etc.).
</p>


<a name="the-call-stack-explained"></a>
<h2>The Call Stack Explained</h2>
<p>
    This text refers to the concept the "call stack" in several places. By the call stack
    is meant the sequence of method calls from the current method and back to the Main method
    of the program. If a method A calls B, and B calls C then the call stack looks like this:
</p>

<pre class="codeBox">
    A
    B
    C
</pre>

<p>
    When method C returns the call stack only contains A and B. If B then calls the method D,
    then the call stack looks like this:
</p>

<pre class="codeBox">
    A
    B
    D
</pre>

<p>
    Understanding the call stack is important when learning the concept of exception propagation.
    Exception are propagated up the call stack, from the method that initially throws it, until
    a method in the call stack catches it. More on that later.
</p>



<a name="throwing-exceptions"></a>
<h2>Throwing Exceptions</h2>
<p>
    If a method needs to be able to throw an exception, it has to declare the exception(s) thrown in the method signature,
    and then include a throw-statement in the method. Here is an example:
</p>

<pre class="codeBox">
    public void divide(int numberToDivide, int numberToDivideBy)
    throws BadNumberException{
        if(numberToDivideBy == 0){
            throw new BadNumberException("Cannot divide by 0");
        }
        return numberToDivide / numberToDivideBy;
    }
</pre>
<p>
    When an exception is thrown the method stops execution right after the "throw" statement.
    Any statements following the "throw" statement are not executed. In the example above
    the "return numberToDivide / numberToDivideBy;" statement is not executed if a
    BadNumberException is thrown.
    The program resumes
    execution when the exception is caught somewhere by a "catch" block. Catching exceptions
    is explained later.
</p>

<p>
    You can throw any type of exception from your code, as long as your method signature
    declares it. You can also make up your own exceptions. Exceptions are regular Java classes
    that extends java.lang.Exception, or any of the other built-in exception classes. If a
    method declares that it throws an exception A, then it is also legal to throw subclasses of
    A.
</p>



<a name="catching-exceptions"></a>
<h2>Catching Exceptions</h2>
<p>
    If a method calls another method that throws checked exceptions, the calling method is forced to
    either pass the exception on, or catch it. Catching the exception is done using a try-catch block.
    Here is an example:
</p>

<pre class="codeBox">
    public void callDivide(){
        try {
            int result = divide(2,1);
            System.out.println(result);
        } catch (BadNumberException e) {
            //do something clever with the exception
            System.out.println(e.getMessage());
        }
        System.out.println("Division attempt done");
    }
</pre>
<p>
    The BadNumberException parameter e inside the catch-clause points to the
    exception thrown from the divide method, if an exception is thrown.
</p>

<p>
    If no exeception is thrown by any of the methods called or
    statements executed inside the try-block, the catch-block
    is simply ignored. It will not be executed.

</p>

<p>
    If an exception is thrown inside the try-block, for instance from
    the divide method, the program
    flow of the calling method, callDivide, is interrupted just like
    the program flow inside divide. The program flow resumes at a catch-block
    in the call stack that can catch the thrown exception.
    In the example above the "System.out.println(result);" statement will
    not get executed if an exception is thrown fromt the divide method.
    Instead program execution will resume inside the
    "catch (BadNumberException e) { }" block.
</p>

<p>
    If an exception is thrown inside the catch-block and that exception is not caught, the catch-block is
    interrupted just like the try-block would have been.
</p>

<p>
    When the catch block is finished
    the program continues with any statements following the catch block.
    In the example above the "System.out.println("Division attempt done");"
    statement will always get executed.
</p>



<a name="propagating-exceptions"></a>
<h2>Propagating Exceptions</h2>
<p>
    You don't have to catch exceptions thrown from other methods. If you cannot do anything
    about the exception where the method throwing it is called, you can just let the method
    propagate the exception up the call stack to the method that called this method. If you do so
    the method calling the method that throws the exception must also declare to throw
    the exception. Here is how the callDivide() method would look in that case.
</p>

<pre class="codeBox">
    public void callDivide() throws BadNumberException{
        int result = divide(2,1);
        System.out.println(result);
    }
</pre>
<p>
    Notice how the try-catch block is gone, and the callDivide method now
    declares that it can throw a BadNumberException. The program execution
    is still interrupted if an exception is thrown from the divide method.
    Thus the "System.out.println(result);" method will not get executed if
    an exception is thrown from the divide method. But now the program execution
    is not resumed inside the callDivide method. The exception is propagated
    to the method that calls callDivide. Program execution
    doesn't resume until a catch-block somewhere in the call stack
    catches the exception. All methods in the call stack
    between the method throwing the exception and the method catching it have their
    execution stopped at the point in the code where the exception is thrown
    or propagated.
</p>



<a name="example-catching-ioexception"></a>
<h2>Example: Catching IOException's</h2>
<p>
    If an exception is thrown during a sequence of statements inside a try-catch block, the sequence of statements
    is interrupted and the flow of control will skip directly to the catch-block. This code can be interrupted
    by exceptions in several places:
</p>

<pre class="codeBox">
    public void openFile(){
        try {
            // constructor may throw FileNotFoundException
            FileReader reader = new FileReader("someFile");
            int i=0;
            while(i != -1){
                //reader.read() may throw IOException
                i = reader.read();
                System.out.println((char) i );
            }
            reader.close();
            System.out.println("--- File End ---");
        } catch (FileNotFoundException e) {
            //do something clever with the exception
        } catch (IOException e) {
            //do something clever with the exception
        }
    }
</pre>

<p>
    If the reader.read() method call throws an IOException, the following System.out.println((char) i );
    is not executed. Neither is the last reader.close() or the System.out.println("--- File End ---");
    statements. Instead the program skips directly to the catch(IOException e){ ... } catch clause.
    If the new FileReader("someFile"); constructor call throws an exception, none of the code inside the
    try-block is executed.
</p>



<a name="example-propagating-ioexception"></a>
<h2>Example: Propagating IOException's</h2>
<p>
    This code is a version of the previous method that throws the exceptions instead of catching them:
</p>

<pre class="codeBox">
    public void openFile() throws IOException {
        FileReader reader = new FileReader("someFile");
        int i=0;
        while(i != -1){
            i = reader.read();
            System.out.println((char) i );
        }
        reader.close();
        System.out.println("--- File End ---");
    }
</pre>

<p>
    If an exception is thrown from the reader.read() method then program execution
    is halted, and the exception is passed up the call stack to the method that called
    openFile(). If the calling method has a try-catch block, the exception will be caught there.
    If the calling method also just throws the method on, the calling method is also interrupted
    at the openFile() method call, and the exception passed on up the call stack. The exception
    is propagated up the call stack like this until some method catches the exception,
    or the Java Virtual Machine does.
</p>



<a name="finally"></a>
<h2>Finally</h2>
<p>
    You can attach a finally-clause to a try-catch block. The code inside the finally clause will
    always be executed, even if an exception is thrown from within the try or catch block. If your
    code has a return statement inside the try or catch block,
    the code inside the finally-block will get executed before returning from the method.

    Here is how a finally
    clause looks:
</p>

<pre class="codeBox">

    public void openFile(){
        FileReader reader = null;
        try {
            reader = new FileReader("someFile");
            int i=0;
            while(i != -1){
                i = reader.read();
                System.out.println((char) i );
            }
        } catch (IOException e) {
            //do something clever with the exception
        } finally {
            if(reader != null){
                try {
                    reader.close();
                } catch (IOException e) {
                    //do something clever with the exception
                }
            }
            System.out.println("--- File End ---");
        }
    }
</pre>

<p>
    No matter whether an exception is thrown or not inside the try or catch block
    the code inside the finally-block is executed. The example above shows
    how the file reader is always closed, regardless of the program flow
    inside the try or catch block.
</p>

<p>
    Note: If an exception is thrown inside a finally block, and it is not caught,
    then that finally block is interrupted just like the try-block and catch-block is.
    That is why the previous example had the reader.close() method call in the finally
    block wrapped in a try-catch block:
</p>

<pre class="codeBox">
    } finally {
            if(reader != null){
                try {
                    reader.close();
                } catch (IOException e) {
                    //do something clever with the exception
                }
            }
            System.out.println("--- File End ---");
        }
</pre>

<p>That way the System.out.println("--- File End ---"); method call will always
    be executed. If no unchecked exceptions are thrown that is. More about
    checked and unchecked in a later chapter.
</p>

<p>
    You don't need both a catch and a finally block. You can have one of them or both
    of them with a try-block, but not none of them. This code doesn't catch the exception but
    lets it propagate up the call stack. Due to the finally block the code
    still closes the filer reader even if an exception is thrown.
</p>

<pre class="codeBox">
    public void openFile() throws IOException {
        FileReader reader = null;
        try {
            reader = new FileReader("someFile");
            int i=0;
            while(i != -1){
                i = reader.read();
                System.out.println((char) i );
            }
        } finally {
            if(reader != null){
                try {
                    reader.close();
                } catch (IOException e) {
                    //do something clever with the exception
                }
            }
            System.out.println("--- File End ---");
        }
    }
</pre>

<p>
    Notice how the catch block is gone.
</p>


<a name="catch-or-propagating-exceptions"></a>
<h2>Catch or Propagate Exceptions?</h2>
<p>
    You might be wondering whether you should catch or propate exceptions thrown in your
    program. It depends on the situation. In many applications you can't really do much
    about the exception but tell the user that the requested action failed. In these
    applications you can usually catch all or most exceptions centrally in one of the
    first methods in the call stack. You may still have to deal with the exception while
    propagating it though (using finally clauses).
    For instance, if an error occurs in the database connection in
    a web application, you may still have to close the database connection in a finally
    clause, even if you can't do anything else than tell the user that the action failed.
    How you end up handling exceptions also depends on whether you choose checked or
    unchecked exceptions for your application. There is more on that in other texts in the error
    handling trail.
</p>

                <div>
                </div>

                <div id="next">Next: <a href="try-with-resources.html">Try-with-resources in Java 7</a></div>
                <div id="bottomSocial">

                    <div style="display:inline-block;">
                        <table>
                            <tr><td colspan="2">
                                <div class='g-plus' data-action='share' data-height='24'  data-annotation='none'></div>
                                <script type='text/javascript'>
                                    (function() {
                                        var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
                                        po.src = 'https://apis.google.com/js/platform.js';
                                        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
                                     })();
                                </script>

                                <a href='https://twitter.com/share' class='twitter-share-button' data-via='jjenkov' target="_blank">Tweet</a>
                                <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>

                            </td></tr>
                            <tr><td class="authorPhoto"></td><td><p style="margin: 0px 0px 6px 0px;">Jakob Jenkov</p><div class="authorSocialLinks"></div></td></tr>
                        </table>
                    </div>

                    <div  style="display: none;" class="newsletterForm"  style="display:inline-block;"></div>

                </div>
            </div>
            </div>
        </div>
    </div>

</div>

<!-- Bottom ads - (nested row is working, but should perhaps not be a nested row?) (note: was a nested row in old design - not in new) -->
<div jqc-row jqc-row-paddings="0:0">
    <div jqc-cell="0:12c">
        <div id="pageBottomAds">
            <script>
                    if(articleLen >= 4000){ /* for longer articles place ads here, at the bottom of the page */
                        if(window.innerWidth >= 728 ) {  /* Adsense Ads - Bottom Banner */
                            if(adRandom < 5)       { writeAd("2721937400", 970, 90);  bottomAdStyles("pageBottomAds", 970, 20, 20);}
                            else if(adRandom < 30) { writeAd("9547200207", 970, 250); bottomAdStyles("pageBottomAds", 970, 20, 20);}
                            else                   { writeAd("7776167002", 728, 90);  bottomAdStyles("pageBottomAds", 728, 20, 20);}
                        } else if(window.innerWidth < 728) {  /* Adsense Ads - Bottom Banner - Mobile */
                            if(adRandom < 50) {
                                writeAd("4216244607", 320, 50); bottomAdStyles("pageBottomAds", 320, 10, 0);
                            } else {
                                writeAd("7377085404", 320, 100); bottomAdStyles("pageBottomAds", 320, 10, 0);
                            }
                        }
                    }
                </script>
            <br/><br/><br/>
        </div>


        <div style="height: 30px"></div>
        <div id="disqusComments" class="card">
            <div id="disqus_thread"></div>
            <script type="text/javascript">
                var disqus_shortname = 'tutorials-jenkov-com'; // required: replace example with your forum shortname

                /* * * DON'T EDIT BELOW THIS LINE * * */
                (function() {
                    var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
                    dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
                    (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
                })();
            </script>
            <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
        </div>

    </div>
</div>

<span id="layoutManager" jqc-type="jqcResponsiveLayoutManager" jqc-row-paddings="0:8 4:0"></span>


<div id="footerBar">
<div jqc-row>
    <div jqc-cell="0:12c">
        Copyright &nbsp;Jenkov Aps
    </div>
</div>
</div>

<div id="trailTocFixedDiv">
  <div id="trailTocFixedCloseButton">Close TOC</div>
  <div id="trailTocFixedInnerDiv"></div>
</div>
<div id="bottomNavBar"></div>

<!-- init page -->
<script>
pageLoaded = true;
init();
</script>


<!-- Google Analytics Script -->
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-4036229-3', 'auto');
  ga('send', 'pageview');

</script>


</body>
</html>
<!-- Localized -->